# Generated by Django 3.2.13 on 2022-06-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reco1', models.CharField(blank=True, max_length=100)),
                ('reco2', models.CharField(blank=True, max_length=100)),
                ('reco3', models.CharField(blank=True, max_length=100)),
                ('reco4', models.CharField(blank=True, max_length=100)),
                ('reco5', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'default_reco',
            },
        ),
    ]
