# Generated by Django 4.0.5 on 2022-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendmodel',
            name='reco',
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='reco1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='reco2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='reco3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='reco4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recommendmodel',
            name='reco5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
