# Generated by Django 3.2.5 on 2022-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('timecost', models.CharField(max_length=30)),
                ('difficulty', models.CharField(max_length=30)),
                ('ingredient', models.TextField()),
                ('cookstep', models.TextField()),
            ],
            options={
                'db_table': 'default_recipe',
            },
        ),
    ]
