# Generated by Django 4.0.5 on 2022-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
