# Generated by Django 4.0.5 on 2022-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_recipe_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_file',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
