# Generated by Django 4.0.5 on 2022-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timecost',
            field=models.CharField(max_length=10),
        ),
    ]
