# Generated by Django 4.0.5 on 2022-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_recipe_difficulty_alter_recipe_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='timecost',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
