# Generated by Django 4.0.5 on 2022-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_recipe_author_remove_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
