# Generated by Django 4.0.5 on 2022-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_recipe_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
