# Generated by Django 4.0.5 on 2022-06-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webScrapping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webScrapping.defaultrecipe')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
