# Generated by Django 4.0.5 on 2022-06-09 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='like_me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='like_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.recipe'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comment_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.recipe'),
        ),
    ]
