# Generated by Django 4.0.5 on 2022-06-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='comment_content',
        ),
    ]
