# Generated by Django 4.0.5 on 2022-06-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_remove_commentmodel_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_content',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
